name: Auto hosting of web documentation

on: push

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                cat src/requirements | xargs -n 1 python -m pip install --upgrade

            - name: Sphinx build
              run: |
                sphinx-build ./docs/source ./docs/build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                publish_branch: gh-pages
                github_token: ${{ secrets.AUTO_RELEASE }}
                publish_dir: docs/build
                force_orphan: true