name: Auto hosting of web documentation

on: [push, pull_request]

permissions:
    contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade sphinx sphinx-rtd-theme

      - name: Check directory
        run: ls -l

      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.AUTO_RELEASE }}
          publish_dir: docs/build
          force_orphan: true